server:
  port: 8081
file:
  upload-path: ./upload/
spring:
  main:
    lazy-initialization: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dicomdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 100000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 100000
      connection-timeout: 30000
      connection-test-query: SELECT 1
